export default [
  { name: 'Dinesh', age: 2000, hobby: 'I like to irritate other people' },
  { name: 'Vineet', age: 65, hobby: 'My Hobby is feka marva' },
  { name: 'iMehul', age: 50, hobby: 'I like to bluff about me and Deepi' },
  { name: 'Jeet', age: 15, hobby: 'I like to follow iMehul-Patel' },
  { name: 'Bhavesh', age: 3, hobby: 'I like to make fun of Rinkal' },
  { name: 'Darshan', age: 40, hobby: 'I like to make people drink salt-water' },
  { name: 'Vishal', age: 21, hobby: 'I like to find Math mistakes in games' },
  { name: 'Ayush', age: 7, hobby: 'I provide lift to Megha' },
  { name: 'Daxesh', age: 23, hobby: 'I like to do jugaad in everything' },
  { name: 'Kaushal', age: 26, hobby: 'I like to give E-commerce tips' },
  { name: 'Rinkal', age: 23, hobby: 'I like to help other people' },
  { name: 'Bhoomi', age: 25, hobby: '' },
  { name: 'Alisha', age: 21, hobby: '' },
  { name: 'Divyesh', age: 25, hobby: '' },
  { name: 'Daxesh-J', age: 21, hobby: '' },
  { name: 'Dimple', age: 25, hobby: '' },
  { name: 'Vikas', age: 25, hobby: '' },
  { name: 'Bhautik', age: 25, hobby: '' },
  { name: 'Shubham', age: 21, hobby: '' },
  { name: 'Hiren', age: 25, hobby: '' },
  { name: 'Kaustubh', age: 25, hobby: '' },
  { name: 'Ashish', age: 25, hobby: '' },
  { name: 'Rakesh', age: 25, hobby: '' },
  { name: 'Kushal', age: 25, hobby: '' },
  { name: 'Ravi', age: 25, hobby: '' },
  { name: 'Khushbu', age: 25, hobby: '' },
  { name: 'Janki', age: 25, hobby: '' },
  { name: 'Kaushik', age: 25, hobby: '' },
  { name: 'Sunil', age: 25, hobby: '' },
  { name: 'Nitin', age: 25, hobby: '' },
  { name: 'Mehul', age: 25, hobby: '' },
  { name: 'Maulik', age: 21, hobby: '' },
  { name: 'Jeny', age: 26, hobby: 'I like to make people happy' },
  { name: 'Yogendra', age: 25, hobby: '' },
  { name: 'Ashish-K', age: 25, hobby: '' }
];
