export default [
  { id: 1, name: 'Dinesh', age: 2000, hobby: 'I just love to irritate rinkal' },
  { id: 2, name: 'Vineet', age: 65, hobby: 'My Hobby is feka marva' },
  { id: 3, name: 'iMehul', age: 50, hobby: 'I like to bluff about me and Deepi' },
  { id: 4, name: 'Jeet', age: 15, hobby: 'I like to follow iMehul-Patel' },
  { id: 5, name: 'Bhavesh', age: 3, hobby: 'I like to make fun of Rinkal' },
  { id: 6, name: 'Darshan', age: 40, hobby: 'I like to make people drink salt-water' },
  { id: 7, name: 'Vishal', age: 21, hobby: 'I like to find Math mistakes in games' },
  { id: 8, name: 'Ayush', age: 7, hobby: 'I provide lift to Megha' },
  { id: 9, name: 'Ayush', age: 7, hobby: 'I like to make sounds like a child' },
  { id: 10, name: 'Daxesh', age: 23, hobby: 'I like to do jugaad in everything' },
  { id: 11, name: 'Kaushal', age: 26, hobby: 'I like to give E-commerce tips' },
  { id: 12, name: 'Rinkal', age: 23, hobby: 'I like to help other people' },
  { id: 13, name: 'Bhoomi', age: 25, hobby: '' },
  { id: 14, name: 'Alisha', age: 21, hobby: '' },
  { id: 15, name: 'Divyesh', age: 25, hobby: '' },
  { id: 16, name: 'Daxesh-J', age: 21, hobby: '' },
  { id: 17, name: 'Dimple', age: 25, hobby: '' },
  { id: 18, name: 'Vikas', age: 25, hobby: '' },
  { id: 19, name: 'Bhautik', age: 25, hobby: '' },
  { id: 20, name: 'Shubham', age: 21, hobby: '' },
  { id: 21, name: 'Hiren', age: 25, hobby: '' },
  { id: 22, name: 'Kaustubh', age: 25, hobby: '' },
  { id: 23, name: 'Ashish', age: 25, hobby: '' },
  { id: 24, name: 'Rakesh', age: 28, hobby: '' },
  { id: 25, name: 'Kushal', age: 28, hobby: '' },
  { id: 26, name: 'Ravi', age: 25, hobby: '' },
  { id: 27, name: 'Khushbu', age: 25, hobby: '' },
  { id: 28, name: 'Janki', age: 25, hobby: '' },
  { id: 29, name: 'Kaushik', age: 25, hobby: '' },
  { id: 30, name: 'Sunil', age: 25, hobby: '' },
  { id: 31, name: 'Nitin', age: 25, hobby: '' },
  { id: 32, name: 'Mehul', age: 25, hobby: '' },
  { id: 33, name: 'Maulik', age: 21, hobby: '' },
  { id: 34, name: 'Jeny', age: 26, hobby: 'I like to make people happy' },
  { id: 35, name: 'Yogendra', age: 25, hobby: '' },
  { id: 36, name: 'Ashish-K', age: 25, hobby: '' }
];
